### ISSUE TITLE
Bedrock type is missing

### ISSUE THREAD

**Issue by phytoclast** [ncss-tech/soilDB#83] opened 2018-10-31 14:04 UTC
The composition of glade plant communities associated with rock outcrops depend on what type of bedrock it is. Since outcrops get no representation in parent material tables, the bedrock influenced soil components in the same map unit contain the only clues regarding the type of bedrock in rock outcrops. I use the parent material group or the parent material origin to determine what type of bedrock is present for bedrock influenced soils (any soil with bedrock in its profile). However, the fetchNASIS function only pulls in PM Kind for the top portion of the profile, rather than using parent material group. Bedrock is indicated as PM Origin only in the layer where the bedrock is present, which is not pulled in by fetchNASIS.

**Comment by phytoclast** [comment] 2018-10-31 14:08
Here is an example:

**Comment by phytoclast** [comment] 2018-10-31 14:08
Apparently an image file cannot be attached?

**Comment by dylanbeaudette** [comment] 2018-10-31 17:06
It is hard to know what the problem is without a simple, reproducible example. For all issues related to NASIS, it is important to include the query + parameters that you were using.

Here is an example component and the flattened result returned by `fetchNASIS`:

![image](https://user-images.githubusercontent.com/624277/47805312-45718a80-dcf4-11e8-8895-05c8e0da3ec5.png)

|compname    |pmkind                           |pmorigin                              |
|:-----------|:--------------------------------|:-------------------------------------|
|Sites       |colluvium & residuum             |metasedimentary, unspecified          |
|Tiger Creek |colluvium & colluvium & residuum |marble & metasedimentary, unspecified |
|Tiger Creek |colluvium & colluvium & residuum |marble & metasedimentary, unspecified |
|Nedsgulch   |colluvium & residuum             |metasedimentary, unspecified          |
|Lickinfork  |colluvium                        |metasedimentary, unspecified          |

Multiple records in the Component Parent Material table are combined into a single `pmkind` and `pmorigin` string by `fetchNASIS`. The order within these strings is based on the Vertical Order column if populated. Note that the Component Parent Material Group table (e.g. NASIS-calculated summary) is not used by `fetchNASIS`.

**Comment by dylanbeaudette** [comment] 2018-10-31 18:57
Thanks for the example. I see the problem, but hesitate to attempt a fix for this specific *corner-case*. Is there any way to fix these kind of data population problems? I made note in a related issue for a full review of the affected functions.

**Comment by phytoclast** [comment] 2018-11-01 17:39
We are not sure what is meant by _corner-case_. The particular record shown for Eleva series is fairly typical for soils around here. The parent material of till and outwash do not have suitable options for the origins field. They would be "mixed" if the option existed. Only when there is bedrock in the profile does origin get used. In the case of a bedrock layer, there is no parent material kind, since it is not yet considered soil. Residuum would certainly be an exception, but most of our bedrock was scraped clean and replaced with till.

**Comment by dylanbeaudette** [comment] 2018-11-01 19:38
Corner-case: records populated in a highly unusual way that isn't accounted for by all of the other special case handling code.

I'll look more closely, but still do not understand how this is anything other than a data population / expectation problem. Give me a call sometime and we can go over the specifics.

As for working with information from OSDs or other work-arounds, see some new functionality in `fetchOSD`:

```r
library(soilDB)
x <- fetchOSD('Eleva', extended = TRUE)
```

```
> x$pmorigin
  series   q_param q_param_n total p
1  ELEVA Sandstone        20    20 1
> x$pmkind
  series                q_param q_param_n total      p
1  ELEVA               Residuum        38    77 0.4935
2  ELEVA              sandstone        13    77 0.1688
3  ELEVA                  Drift         8    77 0.1039
4  ELEVA         Slope alluvium         5    77 0.0649
5  ELEVA        Eolian deposits         4    77 0.0519
6  ELEVA Glaciofluvial deposits         3    77 0.0390
7  ELEVA               Alluvium         3    77 0.0390
8  ELEVA                   Till         3    77 0.0390
```

Or, if you need this kind of information for all series see the source data here: https://github.com/ncss-tech/SoilTaxonomy/tree/master/databases

**Closed** 2019-03-15 22:35 UTC
