### ISSUE TITLE
Draw Water Retention model in example returns error

### ISSUE THREAD

**Issue by TylerGriffin99** [ncss-tech/soilDB#72] opened 2018-08-27 08:53 UTC
The example posted in your readme here http://ncss-tech.github.io/AQP/soilDB/fetchKSSL-VG-demo.html returns the following error when run

Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found

How should the command be changed to get this code to run?

**Comment by brownag** [comment] 2018-08-27 15:47
Hi @TylerGriffin99 

I was unable to reproduce your error. The code for all three plot examples in the van Genuchten demo appears to work as written. 

Are you sure that there aren't other errors occurring before the plotting command fails? Verify that all of the data required to make the plot are present.

Do you have all the latest versions of required packages and their dependencies installed (and none of them failed to install)?

**Comment by dylanbeaudette** [comment] 2018-10-19 18:14
Works for me, but I have seen this error message in some cases. It appears to be an inconsistent graphics state within RStudio. Closing.

**Closed by dylanbeaudette** 2018-10-19 18:14 UTC
